#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Sport")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_Admin(tbl_Admin instance);
  partial void Updatetbl_Admin(tbl_Admin instance);
  partial void Deletetbl_Admin(tbl_Admin instance);
  partial void Inserttbl_User(tbl_User instance);
  partial void Updatetbl_User(tbl_User instance);
  partial void Deletetbl_User(tbl_User instance);
  partial void Inserttbl_CM(tbl_CM instance);
  partial void Updatetbl_CM(tbl_CM instance);
  partial void Deletetbl_CM(tbl_CM instance);
  partial void Inserttbl_CostType(tbl_CostType instance);
  partial void Updatetbl_CostType(tbl_CostType instance);
  partial void Deletetbl_CostType(tbl_CostType instance);
  partial void Inserttbl_ReportsBuyUser(tbl_ReportsBuyUser instance);
  partial void Updatetbl_ReportsBuyUser(tbl_ReportsBuyUser instance);
  partial void Deletetbl_ReportsBuyUser(tbl_ReportsBuyUser instance);
  partial void Inserttbl_San(tbl_San instance);
  partial void Updatetbl_San(tbl_San instance);
  partial void Deletetbl_San(tbl_San instance);
  partial void Inserttbl_SansBuy(tbl_SansBuy instance);
  partial void Updatetbl_SansBuy(tbl_SansBuy instance);
  partial void Deletetbl_SansBuy(tbl_SansBuy instance);
  partial void Inserttbl_SportFild(tbl_SportFild instance);
  partial void Updatetbl_SportFild(tbl_SportFild instance);
  partial void Deletetbl_SportFild(tbl_SportFild instance);
  partial void Inserttbl_Teacher(tbl_Teacher instance);
  partial void Updatetbl_Teacher(tbl_Teacher instance);
  partial void Deletetbl_Teacher(tbl_Teacher instance);
  partial void Inserttbl_TimeUser(tbl_TimeUser instance);
  partial void Updatetbl_TimeUser(tbl_TimeUser instance);
  partial void Deletetbl_TimeUser(tbl_TimeUser instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_SportConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_Admin> tbl_Admins
	{
		get
		{
			return this.GetTable<tbl_Admin>();
		}
	}
	
	public System.Data.Linq.Table<tbl_User> tbl_Users
	{
		get
		{
			return this.GetTable<tbl_User>();
		}
	}
	
	public System.Data.Linq.Table<tbl_CM> tbl_CMs
	{
		get
		{
			return this.GetTable<tbl_CM>();
		}
	}
	
	public System.Data.Linq.Table<tbl_CostType> tbl_CostTypes
	{
		get
		{
			return this.GetTable<tbl_CostType>();
		}
	}
	
	public System.Data.Linq.Table<tbl_ReportsBuyUser> tbl_ReportsBuyUsers
	{
		get
		{
			return this.GetTable<tbl_ReportsBuyUser>();
		}
	}
	
	public System.Data.Linq.Table<tbl_San> tbl_Sans
	{
		get
		{
			return this.GetTable<tbl_San>();
		}
	}
	
	public System.Data.Linq.Table<tbl_SansBuy> tbl_SansBuys
	{
		get
		{
			return this.GetTable<tbl_SansBuy>();
		}
	}
	
	public System.Data.Linq.Table<tbl_SportFild> tbl_SportFilds
	{
		get
		{
			return this.GetTable<tbl_SportFild>();
		}
	}
	
	public System.Data.Linq.Table<tbl_Teacher> tbl_Teachers
	{
		get
		{
			return this.GetTable<tbl_Teacher>();
		}
	}
	
	public System.Data.Linq.Table<tbl_TimeUser> tbl_TimeUsers
	{
		get
		{
			return this.GetTable<tbl_TimeUser>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Admins")]
public partial class tbl_Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _FullName;
	
	private string _UserName;
	
	private string _Password;
	
	private string _Codey;
	
	private int _GymID;
	
	private string _Code;
	
	private string _N_Phone;
	
	private string _N_Home;
	
	private string _Address;
	
	private string _img;
	
	private int _AdminLevel;
	
	private string _D_Birth;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _Marital;
	
	private string _FullNameGym;
	
	private string _N_PhoneGym;
	
	private string _AddressGym;
	
	private string _DescriptionGym;
	
	private string _R_DateGym;
	
	private string _E_DateGym;
	
	private int _DebtGym;
	
	private int _Active;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCodeyChanging(string value);
    partial void OnCodeyChanged();
    partial void OnGymIDChanging(int value);
    partial void OnGymIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnN_PhoneChanging(string value);
    partial void OnN_PhoneChanged();
    partial void OnN_HomeChanging(string value);
    partial void OnN_HomeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnAdminLevelChanging(int value);
    partial void OnAdminLevelChanged();
    partial void OnD_BirthChanging(string value);
    partial void OnD_BirthChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnMaritalChanging(System.Nullable<int> value);
    partial void OnMaritalChanged();
    partial void OnFullNameGymChanging(string value);
    partial void OnFullNameGymChanged();
    partial void OnN_PhoneGymChanging(string value);
    partial void OnN_PhoneGymChanged();
    partial void OnAddressGymChanging(string value);
    partial void OnAddressGymChanged();
    partial void OnDescriptionGymChanging(string value);
    partial void OnDescriptionGymChanged();
    partial void OnR_DateGymChanging(string value);
    partial void OnR_DateGymChanged();
    partial void OnE_DateGymChanging(string value);
    partial void OnE_DateGymChanged();
    partial void OnDebtGymChanging(int value);
    partial void OnDebtGymChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Codey
	{
		get
		{
			return this._Codey;
		}
		set
		{
			if ((this._Codey != value))
			{
				this.OnCodeyChanging(value);
				this.SendPropertyChanging();
				this._Codey = value;
				this.SendPropertyChanged("Codey");
				this.OnCodeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GymID", DbType="Int NOT NULL")]
	public int GymID
	{
		get
		{
			return this._GymID;
		}
		set
		{
			if ((this._GymID != value))
			{
				this.OnGymIDChanging(value);
				this.SendPropertyChanging();
				this._GymID = value;
				this.SendPropertyChanged("GymID");
				this.OnGymIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Phone", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string N_Phone
	{
		get
		{
			return this._N_Phone;
		}
		set
		{
			if ((this._N_Phone != value))
			{
				this.OnN_PhoneChanging(value);
				this.SendPropertyChanging();
				this._N_Phone = value;
				this.SendPropertyChanged("N_Phone");
				this.OnN_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Home", DbType="NVarChar(15)")]
	public string N_Home
	{
		get
		{
			return this._N_Home;
		}
		set
		{
			if ((this._N_Home != value))
			{
				this.OnN_HomeChanging(value);
				this.SendPropertyChanging();
				this._N_Home = value;
				this.SendPropertyChanged("N_Home");
				this.OnN_HomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(150)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this.OnimgChanging(value);
				this.SendPropertyChanging();
				this._img = value;
				this.SendPropertyChanged("img");
				this.OnimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminLevel", DbType="Int NOT NULL")]
	public int AdminLevel
	{
		get
		{
			return this._AdminLevel;
		}
		set
		{
			if ((this._AdminLevel != value))
			{
				this.OnAdminLevelChanging(value);
				this.SendPropertyChanging();
				this._AdminLevel = value;
				this.SendPropertyChanged("AdminLevel");
				this.OnAdminLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Birth", DbType="NVarChar(50)")]
	public string D_Birth
	{
		get
		{
			return this._D_Birth;
		}
		set
		{
			if ((this._D_Birth != value))
			{
				this.OnD_BirthChanging(value);
				this.SendPropertyChanging();
				this._D_Birth = value;
				this.SendPropertyChanged("D_Birth");
				this.OnD_BirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marital", DbType="Int")]
	public System.Nullable<int> Marital
	{
		get
		{
			return this._Marital;
		}
		set
		{
			if ((this._Marital != value))
			{
				this.OnMaritalChanging(value);
				this.SendPropertyChanging();
				this._Marital = value;
				this.SendPropertyChanged("Marital");
				this.OnMaritalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameGym", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
	public string FullNameGym
	{
		get
		{
			return this._FullNameGym;
		}
		set
		{
			if ((this._FullNameGym != value))
			{
				this.OnFullNameGymChanging(value);
				this.SendPropertyChanging();
				this._FullNameGym = value;
				this.SendPropertyChanged("FullNameGym");
				this.OnFullNameGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_PhoneGym", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string N_PhoneGym
	{
		get
		{
			return this._N_PhoneGym;
		}
		set
		{
			if ((this._N_PhoneGym != value))
			{
				this.OnN_PhoneGymChanging(value);
				this.SendPropertyChanging();
				this._N_PhoneGym = value;
				this.SendPropertyChanged("N_PhoneGym");
				this.OnN_PhoneGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressGym", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string AddressGym
	{
		get
		{
			return this._AddressGym;
		}
		set
		{
			if ((this._AddressGym != value))
			{
				this.OnAddressGymChanging(value);
				this.SendPropertyChanging();
				this._AddressGym = value;
				this.SendPropertyChanged("AddressGym");
				this.OnAddressGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionGym", DbType="NVarChar(MAX)")]
	public string DescriptionGym
	{
		get
		{
			return this._DescriptionGym;
		}
		set
		{
			if ((this._DescriptionGym != value))
			{
				this.OnDescriptionGymChanging(value);
				this.SendPropertyChanging();
				this._DescriptionGym = value;
				this.SendPropertyChanged("DescriptionGym");
				this.OnDescriptionGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_DateGym", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string R_DateGym
	{
		get
		{
			return this._R_DateGym;
		}
		set
		{
			if ((this._R_DateGym != value))
			{
				this.OnR_DateGymChanging(value);
				this.SendPropertyChanging();
				this._R_DateGym = value;
				this.SendPropertyChanged("R_DateGym");
				this.OnR_DateGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DateGym", DbType="NVarChar(50)")]
	public string E_DateGym
	{
		get
		{
			return this._E_DateGym;
		}
		set
		{
			if ((this._E_DateGym != value))
			{
				this.OnE_DateGymChanging(value);
				this.SendPropertyChanging();
				this._E_DateGym = value;
				this.SendPropertyChanged("E_DateGym");
				this.OnE_DateGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebtGym", DbType="Int NOT NULL")]
	public int DebtGym
	{
		get
		{
			return this._DebtGym;
		}
		set
		{
			if ((this._DebtGym != value))
			{
				this.OnDebtGymChanging(value);
				this.SendPropertyChanging();
				this._DebtGym = value;
				this.SendPropertyChanged("DebtGym");
				this.OnDebtGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
	public int Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User")]
public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _FullName;
	
	private string _UserName;
	
	private string _Password;
	
	private string _Code;
	
	private System.Nullable<int> _R_Code;
	
	private string _R_Date;
	
	private string _N_Phone;
	
	private string _N_Home;
	
	private string _Email;
	
	private string _Address;
	
	private string _Description;
	
	private string _Codey;
	
	private string _D_Birth;
	
	private string _G_Blood;
	
	private string _N_Insurance;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _Marital;
	
	private string _D_E_Insurance;
	
	private string _img;
	
	private System.Nullable<int> _GymID;
	
	private int _Deleted;
	
	private int _OkAdmin;
	
	private int _FullItem;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnR_CodeChanging(System.Nullable<int> value);
    partial void OnR_CodeChanged();
    partial void OnR_DateChanging(string value);
    partial void OnR_DateChanged();
    partial void OnN_PhoneChanging(string value);
    partial void OnN_PhoneChanged();
    partial void OnN_HomeChanging(string value);
    partial void OnN_HomeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCodeyChanging(string value);
    partial void OnCodeyChanged();
    partial void OnD_BirthChanging(string value);
    partial void OnD_BirthChanged();
    partial void OnG_BloodChanging(string value);
    partial void OnG_BloodChanged();
    partial void OnN_InsuranceChanging(string value);
    partial void OnN_InsuranceChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnMaritalChanging(System.Nullable<int> value);
    partial void OnMaritalChanged();
    partial void OnD_E_InsuranceChanging(string value);
    partial void OnD_E_InsuranceChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnGymIDChanging(System.Nullable<int> value);
    partial void OnGymIDChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    partial void OnOkAdminChanging(int value);
    partial void OnOkAdminChanged();
    partial void OnFullItemChanging(int value);
    partial void OnFullItemChanged();
    #endregion
	
	public tbl_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(350)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(MAX)")]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Code", DbType="Int")]
	public System.Nullable<int> R_Code
	{
		get
		{
			return this._R_Code;
		}
		set
		{
			if ((this._R_Code != value))
			{
				this.OnR_CodeChanging(value);
				this.SendPropertyChanging();
				this._R_Code = value;
				this.SendPropertyChanged("R_Code");
				this.OnR_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Date", DbType="NVarChar(50)")]
	public string R_Date
	{
		get
		{
			return this._R_Date;
		}
		set
		{
			if ((this._R_Date != value))
			{
				this.OnR_DateChanging(value);
				this.SendPropertyChanging();
				this._R_Date = value;
				this.SendPropertyChanged("R_Date");
				this.OnR_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Phone", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string N_Phone
	{
		get
		{
			return this._N_Phone;
		}
		set
		{
			if ((this._N_Phone != value))
			{
				this.OnN_PhoneChanging(value);
				this.SendPropertyChanging();
				this._N_Phone = value;
				this.SendPropertyChanged("N_Phone");
				this.OnN_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Home", DbType="NVarChar(15)")]
	public string N_Home
	{
		get
		{
			return this._N_Home;
		}
		set
		{
			if ((this._N_Home != value))
			{
				this.OnN_HomeChanging(value);
				this.SendPropertyChanging();
				this._N_Home = value;
				this.SendPropertyChanged("N_Home");
				this.OnN_HomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(300)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Codey
	{
		get
		{
			return this._Codey;
		}
		set
		{
			if ((this._Codey != value))
			{
				this.OnCodeyChanging(value);
				this.SendPropertyChanging();
				this._Codey = value;
				this.SendPropertyChanged("Codey");
				this.OnCodeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Birth", DbType="NVarChar(50)")]
	public string D_Birth
	{
		get
		{
			return this._D_Birth;
		}
		set
		{
			if ((this._D_Birth != value))
			{
				this.OnD_BirthChanging(value);
				this.SendPropertyChanging();
				this._D_Birth = value;
				this.SendPropertyChanged("D_Birth");
				this.OnD_BirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_Blood", DbType="NVarChar(50)")]
	public string G_Blood
	{
		get
		{
			return this._G_Blood;
		}
		set
		{
			if ((this._G_Blood != value))
			{
				this.OnG_BloodChanging(value);
				this.SendPropertyChanging();
				this._G_Blood = value;
				this.SendPropertyChanged("G_Blood");
				this.OnG_BloodChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Insurance", DbType="NVarChar(150)")]
	public string N_Insurance
	{
		get
		{
			return this._N_Insurance;
		}
		set
		{
			if ((this._N_Insurance != value))
			{
				this.OnN_InsuranceChanging(value);
				this.SendPropertyChanging();
				this._N_Insurance = value;
				this.SendPropertyChanged("N_Insurance");
				this.OnN_InsuranceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marital", DbType="Int")]
	public System.Nullable<int> Marital
	{
		get
		{
			return this._Marital;
		}
		set
		{
			if ((this._Marital != value))
			{
				this.OnMaritalChanging(value);
				this.SendPropertyChanging();
				this._Marital = value;
				this.SendPropertyChanged("Marital");
				this.OnMaritalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_E_Insurance", DbType="NVarChar(50)")]
	public string D_E_Insurance
	{
		get
		{
			return this._D_E_Insurance;
		}
		set
		{
			if ((this._D_E_Insurance != value))
			{
				this.OnD_E_InsuranceChanging(value);
				this.SendPropertyChanging();
				this._D_E_Insurance = value;
				this.SendPropertyChanged("D_E_Insurance");
				this.OnD_E_InsuranceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this.OnimgChanging(value);
				this.SendPropertyChanging();
				this._img = value;
				this.SendPropertyChanged("img");
				this.OnimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GymID", DbType="Int")]
	public System.Nullable<int> GymID
	{
		get
		{
			return this._GymID;
		}
		set
		{
			if ((this._GymID != value))
			{
				this.OnGymIDChanging(value);
				this.SendPropertyChanging();
				this._GymID = value;
				this.SendPropertyChanged("GymID");
				this.OnGymIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkAdmin", DbType="Int NOT NULL")]
	public int OkAdmin
	{
		get
		{
			return this._OkAdmin;
		}
		set
		{
			if ((this._OkAdmin != value))
			{
				this.OnOkAdminChanging(value);
				this.SendPropertyChanging();
				this._OkAdmin = value;
				this.SendPropertyChanged("OkAdmin");
				this.OnOkAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullItem", DbType="Int NOT NULL")]
	public int FullItem
	{
		get
		{
			return this._FullItem;
		}
		set
		{
			if ((this._FullItem != value))
			{
				this.OnFullItemChanging(value);
				this.SendPropertyChanging();
				this._FullItem = value;
				this.SendPropertyChanged("FullItem");
				this.OnFullItemChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CMS")]
public partial class tbl_CM : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _PanelTitel;
	
	private string _TextFoter;
	
	private string _imgTitel;
	
	private string _Slidimg1;
	
	private string _Slidimg2;
	
	private string _Slidimg3;
	
	private string _TitelMinAbut;
	
	private string _TextMinAbut;
	
	private string _imgMinAbut;
	
	private string _TitelCart;
	
	private string _TextCart;
	
	private string _Description;
	
	private string _Address;
	
	private string _NumberPhone;
	
	private string _FoterMain;
	
	private string _ATitel;
	
	private string _AText;
	
	private string _ATitel1;
	
	private string _AText1;
	
	private string _ATitel2;
	
	private string _AText2;
	
	private string _ATitel3;
	
	private string _AText3;
	
	private string _ATitelCart;
	
	private string _ATextCart;
	
	private string _MapX;
	
	private string _MapY;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPanelTitelChanging(string value);
    partial void OnPanelTitelChanged();
    partial void OnTextFoterChanging(string value);
    partial void OnTextFoterChanged();
    partial void OnimgTitelChanging(string value);
    partial void OnimgTitelChanged();
    partial void OnSlidimg1Changing(string value);
    partial void OnSlidimg1Changed();
    partial void OnSlidimg2Changing(string value);
    partial void OnSlidimg2Changed();
    partial void OnSlidimg3Changing(string value);
    partial void OnSlidimg3Changed();
    partial void OnTitelMinAbutChanging(string value);
    partial void OnTitelMinAbutChanged();
    partial void OnTextMinAbutChanging(string value);
    partial void OnTextMinAbutChanged();
    partial void OnimgMinAbutChanging(string value);
    partial void OnimgMinAbutChanged();
    partial void OnTitelCartChanging(string value);
    partial void OnTitelCartChanged();
    partial void OnTextCartChanging(string value);
    partial void OnTextCartChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNumberPhoneChanging(string value);
    partial void OnNumberPhoneChanged();
    partial void OnFoterMainChanging(string value);
    partial void OnFoterMainChanged();
    partial void OnATitelChanging(string value);
    partial void OnATitelChanged();
    partial void OnATextChanging(string value);
    partial void OnATextChanged();
    partial void OnATitel1Changing(string value);
    partial void OnATitel1Changed();
    partial void OnAText1Changing(string value);
    partial void OnAText1Changed();
    partial void OnATitel2Changing(string value);
    partial void OnATitel2Changed();
    partial void OnAText2Changing(string value);
    partial void OnAText2Changed();
    partial void OnATitel3Changing(string value);
    partial void OnATitel3Changed();
    partial void OnAText3Changing(string value);
    partial void OnAText3Changed();
    partial void OnATitelCartChanging(string value);
    partial void OnATitelCartChanged();
    partial void OnATextCartChanging(string value);
    partial void OnATextCartChanged();
    partial void OnMapXChanging(string value);
    partial void OnMapXChanged();
    partial void OnMapYChanging(string value);
    partial void OnMapYChanged();
    #endregion
	
	public tbl_CM()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanelTitel", DbType="NVarChar(MAX)")]
	public string PanelTitel
	{
		get
		{
			return this._PanelTitel;
		}
		set
		{
			if ((this._PanelTitel != value))
			{
				this.OnPanelTitelChanging(value);
				this.SendPropertyChanging();
				this._PanelTitel = value;
				this.SendPropertyChanged("PanelTitel");
				this.OnPanelTitelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextFoter", DbType="NVarChar(MAX)")]
	public string TextFoter
	{
		get
		{
			return this._TextFoter;
		}
		set
		{
			if ((this._TextFoter != value))
			{
				this.OnTextFoterChanging(value);
				this.SendPropertyChanging();
				this._TextFoter = value;
				this.SendPropertyChanged("TextFoter");
				this.OnTextFoterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgTitel", DbType="NVarChar(MAX)")]
	public string imgTitel
	{
		get
		{
			return this._imgTitel;
		}
		set
		{
			if ((this._imgTitel != value))
			{
				this.OnimgTitelChanging(value);
				this.SendPropertyChanging();
				this._imgTitel = value;
				this.SendPropertyChanged("imgTitel");
				this.OnimgTitelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slidimg1", DbType="NVarChar(MAX)")]
	public string Slidimg1
	{
		get
		{
			return this._Slidimg1;
		}
		set
		{
			if ((this._Slidimg1 != value))
			{
				this.OnSlidimg1Changing(value);
				this.SendPropertyChanging();
				this._Slidimg1 = value;
				this.SendPropertyChanged("Slidimg1");
				this.OnSlidimg1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slidimg2", DbType="NVarChar(MAX)")]
	public string Slidimg2
	{
		get
		{
			return this._Slidimg2;
		}
		set
		{
			if ((this._Slidimg2 != value))
			{
				this.OnSlidimg2Changing(value);
				this.SendPropertyChanging();
				this._Slidimg2 = value;
				this.SendPropertyChanged("Slidimg2");
				this.OnSlidimg2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slidimg3", DbType="NVarChar(MAX)")]
	public string Slidimg3
	{
		get
		{
			return this._Slidimg3;
		}
		set
		{
			if ((this._Slidimg3 != value))
			{
				this.OnSlidimg3Changing(value);
				this.SendPropertyChanging();
				this._Slidimg3 = value;
				this.SendPropertyChanged("Slidimg3");
				this.OnSlidimg3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitelMinAbut", DbType="NVarChar(MAX)")]
	public string TitelMinAbut
	{
		get
		{
			return this._TitelMinAbut;
		}
		set
		{
			if ((this._TitelMinAbut != value))
			{
				this.OnTitelMinAbutChanging(value);
				this.SendPropertyChanging();
				this._TitelMinAbut = value;
				this.SendPropertyChanged("TitelMinAbut");
				this.OnTitelMinAbutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextMinAbut", DbType="NVarChar(MAX)")]
	public string TextMinAbut
	{
		get
		{
			return this._TextMinAbut;
		}
		set
		{
			if ((this._TextMinAbut != value))
			{
				this.OnTextMinAbutChanging(value);
				this.SendPropertyChanging();
				this._TextMinAbut = value;
				this.SendPropertyChanged("TextMinAbut");
				this.OnTextMinAbutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgMinAbut", DbType="NVarChar(MAX)")]
	public string imgMinAbut
	{
		get
		{
			return this._imgMinAbut;
		}
		set
		{
			if ((this._imgMinAbut != value))
			{
				this.OnimgMinAbutChanging(value);
				this.SendPropertyChanging();
				this._imgMinAbut = value;
				this.SendPropertyChanged("imgMinAbut");
				this.OnimgMinAbutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitelCart", DbType="NVarChar(MAX)")]
	public string TitelCart
	{
		get
		{
			return this._TitelCart;
		}
		set
		{
			if ((this._TitelCart != value))
			{
				this.OnTitelCartChanging(value);
				this.SendPropertyChanging();
				this._TitelCart = value;
				this.SendPropertyChanged("TitelCart");
				this.OnTitelCartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextCart", DbType="NVarChar(MAX)")]
	public string TextCart
	{
		get
		{
			return this._TextCart;
		}
		set
		{
			if ((this._TextCart != value))
			{
				this.OnTextCartChanging(value);
				this.SendPropertyChanging();
				this._TextCart = value;
				this.SendPropertyChanged("TextCart");
				this.OnTextCartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberPhone", DbType="NVarChar(MAX)")]
	public string NumberPhone
	{
		get
		{
			return this._NumberPhone;
		}
		set
		{
			if ((this._NumberPhone != value))
			{
				this.OnNumberPhoneChanging(value);
				this.SendPropertyChanging();
				this._NumberPhone = value;
				this.SendPropertyChanged("NumberPhone");
				this.OnNumberPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoterMain", DbType="NVarChar(MAX)")]
	public string FoterMain
	{
		get
		{
			return this._FoterMain;
		}
		set
		{
			if ((this._FoterMain != value))
			{
				this.OnFoterMainChanging(value);
				this.SendPropertyChanging();
				this._FoterMain = value;
				this.SendPropertyChanged("FoterMain");
				this.OnFoterMainChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATitel", DbType="NVarChar(MAX)")]
	public string ATitel
	{
		get
		{
			return this._ATitel;
		}
		set
		{
			if ((this._ATitel != value))
			{
				this.OnATitelChanging(value);
				this.SendPropertyChanging();
				this._ATitel = value;
				this.SendPropertyChanged("ATitel");
				this.OnATitelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AText", DbType="NVarChar(MAX)")]
	public string AText
	{
		get
		{
			return this._AText;
		}
		set
		{
			if ((this._AText != value))
			{
				this.OnATextChanging(value);
				this.SendPropertyChanging();
				this._AText = value;
				this.SendPropertyChanged("AText");
				this.OnATextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATitel1", DbType="NVarChar(MAX)")]
	public string ATitel1
	{
		get
		{
			return this._ATitel1;
		}
		set
		{
			if ((this._ATitel1 != value))
			{
				this.OnATitel1Changing(value);
				this.SendPropertyChanging();
				this._ATitel1 = value;
				this.SendPropertyChanged("ATitel1");
				this.OnATitel1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AText1", DbType="NVarChar(MAX)")]
	public string AText1
	{
		get
		{
			return this._AText1;
		}
		set
		{
			if ((this._AText1 != value))
			{
				this.OnAText1Changing(value);
				this.SendPropertyChanging();
				this._AText1 = value;
				this.SendPropertyChanged("AText1");
				this.OnAText1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATitel2", DbType="NVarChar(MAX)")]
	public string ATitel2
	{
		get
		{
			return this._ATitel2;
		}
		set
		{
			if ((this._ATitel2 != value))
			{
				this.OnATitel2Changing(value);
				this.SendPropertyChanging();
				this._ATitel2 = value;
				this.SendPropertyChanged("ATitel2");
				this.OnATitel2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AText2", DbType="NVarChar(MAX)")]
	public string AText2
	{
		get
		{
			return this._AText2;
		}
		set
		{
			if ((this._AText2 != value))
			{
				this.OnAText2Changing(value);
				this.SendPropertyChanging();
				this._AText2 = value;
				this.SendPropertyChanged("AText2");
				this.OnAText2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATitel3", DbType="NVarChar(MAX)")]
	public string ATitel3
	{
		get
		{
			return this._ATitel3;
		}
		set
		{
			if ((this._ATitel3 != value))
			{
				this.OnATitel3Changing(value);
				this.SendPropertyChanging();
				this._ATitel3 = value;
				this.SendPropertyChanged("ATitel3");
				this.OnATitel3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AText3", DbType="NVarChar(MAX)")]
	public string AText3
	{
		get
		{
			return this._AText3;
		}
		set
		{
			if ((this._AText3 != value))
			{
				this.OnAText3Changing(value);
				this.SendPropertyChanging();
				this._AText3 = value;
				this.SendPropertyChanged("AText3");
				this.OnAText3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATitelCart", DbType="NVarChar(MAX)")]
	public string ATitelCart
	{
		get
		{
			return this._ATitelCart;
		}
		set
		{
			if ((this._ATitelCart != value))
			{
				this.OnATitelCartChanging(value);
				this.SendPropertyChanging();
				this._ATitelCart = value;
				this.SendPropertyChanged("ATitelCart");
				this.OnATitelCartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATextCart", DbType="NVarChar(MAX)")]
	public string ATextCart
	{
		get
		{
			return this._ATextCart;
		}
		set
		{
			if ((this._ATextCart != value))
			{
				this.OnATextCartChanging(value);
				this.SendPropertyChanging();
				this._ATextCart = value;
				this.SendPropertyChanged("ATextCart");
				this.OnATextCartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapX", DbType="NVarChar(MAX)")]
	public string MapX
	{
		get
		{
			return this._MapX;
		}
		set
		{
			if ((this._MapX != value))
			{
				this.OnMapXChanging(value);
				this.SendPropertyChanging();
				this._MapX = value;
				this.SendPropertyChanged("MapX");
				this.OnMapXChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapY", DbType="NVarChar(MAX)")]
	public string MapY
	{
		get
		{
			return this._MapY;
		}
		set
		{
			if ((this._MapY != value))
			{
				this.OnMapYChanging(value);
				this.SendPropertyChanging();
				this._MapY = value;
				this.SendPropertyChanged("MapY");
				this.OnMapYChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CostType")]
public partial class tbl_CostType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Type;
	
	private string _Code;
	
	private int _Gym;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnGymChanging(int value);
    partial void OnGymChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_CostType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gym", DbType="Int NOT NULL")]
	public int Gym
	{
		get
		{
			return this._Gym;
		}
		set
		{
			if ((this._Gym != value))
			{
				this.OnGymChanging(value);
				this.SendPropertyChanging();
				this._Gym = value;
				this.SendPropertyChanged("Gym");
				this.OnGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ReportsBuyUser")]
public partial class tbl_ReportsBuyUser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Date;
	
	private int _Result;
	
	private string _N_Buy;
	
	private string _Money;
	
	private int _UserID;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnResultChanging(int value);
    partial void OnResultChanged();
    partial void OnN_BuyChanging(string value);
    partial void OnN_BuyChanged();
    partial void OnMoneyChanging(string value);
    partial void OnMoneyChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_ReportsBuyUser()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
	public int Result
	{
		get
		{
			return this._Result;
		}
		set
		{
			if ((this._Result != value))
			{
				this.OnResultChanging(value);
				this.SendPropertyChanging();
				this._Result = value;
				this.SendPropertyChanged("Result");
				this.OnResultChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Buy", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
	public string N_Buy
	{
		get
		{
			return this._N_Buy;
		}
		set
		{
			if ((this._N_Buy != value))
			{
				this.OnN_BuyChanging(value);
				this.SendPropertyChanging();
				this._N_Buy = value;
				this.SendPropertyChanged("N_Buy");
				this.OnN_BuyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string Money
	{
		get
		{
			return this._Money;
		}
		set
		{
			if ((this._Money != value))
			{
				this.OnMoneyChanging(value);
				this.SendPropertyChanging();
				this._Money = value;
				this.SendPropertyChanged("Money");
				this.OnMoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
	public int UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Sans")]
public partial class tbl_San : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _FullName;
	
	private string _Code;
	
	private int _SportFildID;
	
	private string _SportFild;
	
	private int _GymID;
	
	private string _Gym;
	
	private string _Techare;
	
	private System.Nullable<int> _TechareID;
	
	private int _Gender;
	
	private string _D_Start;
	
	private string _D_End;
	
	private string _Days;
	
	private int _Mony;
	
	private int _CostTypeID;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnSportFildIDChanging(int value);
    partial void OnSportFildIDChanged();
    partial void OnSportFildChanging(string value);
    partial void OnSportFildChanged();
    partial void OnGymIDChanging(int value);
    partial void OnGymIDChanged();
    partial void OnGymChanging(string value);
    partial void OnGymChanged();
    partial void OnTechareChanging(string value);
    partial void OnTechareChanged();
    partial void OnTechareIDChanging(System.Nullable<int> value);
    partial void OnTechareIDChanged();
    partial void OnGenderChanging(int value);
    partial void OnGenderChanged();
    partial void OnD_StartChanging(string value);
    partial void OnD_StartChanged();
    partial void OnD_EndChanging(string value);
    partial void OnD_EndChanged();
    partial void OnDaysChanging(string value);
    partial void OnDaysChanged();
    partial void OnMonyChanging(int value);
    partial void OnMonyChanged();
    partial void OnCostTypeIDChanging(int value);
    partial void OnCostTypeIDChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_San()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(350) NOT NULL", CanBeNull=false)]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportFildID", DbType="Int NOT NULL")]
	public int SportFildID
	{
		get
		{
			return this._SportFildID;
		}
		set
		{
			if ((this._SportFildID != value))
			{
				this.OnSportFildIDChanging(value);
				this.SendPropertyChanging();
				this._SportFildID = value;
				this.SendPropertyChanged("SportFildID");
				this.OnSportFildIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportFild", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string SportFild
	{
		get
		{
			return this._SportFild;
		}
		set
		{
			if ((this._SportFild != value))
			{
				this.OnSportFildChanging(value);
				this.SendPropertyChanging();
				this._SportFild = value;
				this.SendPropertyChanged("SportFild");
				this.OnSportFildChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GymID", DbType="Int NOT NULL")]
	public int GymID
	{
		get
		{
			return this._GymID;
		}
		set
		{
			if ((this._GymID != value))
			{
				this.OnGymIDChanging(value);
				this.SendPropertyChanging();
				this._GymID = value;
				this.SendPropertyChanged("GymID");
				this.OnGymIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gym", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Gym
	{
		get
		{
			return this._Gym;
		}
		set
		{
			if ((this._Gym != value))
			{
				this.OnGymChanging(value);
				this.SendPropertyChanging();
				this._Gym = value;
				this.SendPropertyChanged("Gym");
				this.OnGymChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Techare", DbType="NVarChar(250)")]
	public string Techare
	{
		get
		{
			return this._Techare;
		}
		set
		{
			if ((this._Techare != value))
			{
				this.OnTechareChanging(value);
				this.SendPropertyChanging();
				this._Techare = value;
				this.SendPropertyChanged("Techare");
				this.OnTechareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechareID", DbType="Int")]
	public System.Nullable<int> TechareID
	{
		get
		{
			return this._TechareID;
		}
		set
		{
			if ((this._TechareID != value))
			{
				this.OnTechareIDChanging(value);
				this.SendPropertyChanging();
				this._TechareID = value;
				this.SendPropertyChanged("TechareID");
				this.OnTechareIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int NOT NULL")]
	public int Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Start", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string D_Start
	{
		get
		{
			return this._D_Start;
		}
		set
		{
			if ((this._D_Start != value))
			{
				this.OnD_StartChanging(value);
				this.SendPropertyChanging();
				this._D_Start = value;
				this.SendPropertyChanged("D_Start");
				this.OnD_StartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_End", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string D_End
	{
		get
		{
			return this._D_End;
		}
		set
		{
			if ((this._D_End != value))
			{
				this.OnD_EndChanging(value);
				this.SendPropertyChanging();
				this._D_End = value;
				this.SendPropertyChanged("D_End");
				this.OnD_EndChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Days", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Days
	{
		get
		{
			return this._Days;
		}
		set
		{
			if ((this._Days != value))
			{
				this.OnDaysChanging(value);
				this.SendPropertyChanging();
				this._Days = value;
				this.SendPropertyChanged("Days");
				this.OnDaysChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mony", DbType="Int NOT NULL")]
	public int Mony
	{
		get
		{
			return this._Mony;
		}
		set
		{
			if ((this._Mony != value))
			{
				this.OnMonyChanging(value);
				this.SendPropertyChanging();
				this._Mony = value;
				this.SendPropertyChanged("Mony");
				this.OnMonyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostTypeID", DbType="Int NOT NULL")]
	public int CostTypeID
	{
		get
		{
			return this._CostTypeID;
		}
		set
		{
			if ((this._CostTypeID != value))
			{
				this.OnCostTypeIDChanging(value);
				this.SendPropertyChanging();
				this._CostTypeID = value;
				this.SendPropertyChanged("CostTypeID");
				this.OnCostTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SansBuy")]
public partial class tbl_SansBuy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private int _SansID;
	
	private int _UserID;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSansIDChanging(int value);
    partial void OnSansIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_SansBuy()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SansID", DbType="Int NOT NULL")]
	public int SansID
	{
		get
		{
			return this._SansID;
		}
		set
		{
			if ((this._SansID != value))
			{
				this.OnSansIDChanging(value);
				this.SendPropertyChanging();
				this._SansID = value;
				this.SendPropertyChanged("SansID");
				this.OnSansIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
	public int UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SportFild")]
public partial class tbl_SportFild : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private int _GymID;
	
	private string _Code;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGymIDChanging(int value);
    partial void OnGymIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_SportFild()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GymID", DbType="Int NOT NULL")]
	public int GymID
	{
		get
		{
			return this._GymID;
		}
		set
		{
			if ((this._GymID != value))
			{
				this.OnGymIDChanging(value);
				this.SendPropertyChanging();
				this._GymID = value;
				this.SendPropertyChanged("GymID");
				this.OnGymIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Teacher")]
public partial class tbl_Teacher : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _FullName;
	
	private string _UserName;
	
	private string _Password;
	
	private string _Code;
	
	private System.Nullable<int> _R_Code;
	
	private string _R_Date;
	
	private string _N_Phone;
	
	private string _N_Home;
	
	private string _Email;
	
	private string _Address;
	
	private string _Description;
	
	private string _Codey;
	
	private string _D_Birth;
	
	private string _G_Blood;
	
	private string _N_Insurance;
	
	private int _Gender;
	
	private int _Marital;
	
	private string _D_E_Insurance;
	
	private string _img;
	
	private int _Gym_ID;
	
	private int _Deleted;
	
	private int _FullItem;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnR_CodeChanging(System.Nullable<int> value);
    partial void OnR_CodeChanged();
    partial void OnR_DateChanging(string value);
    partial void OnR_DateChanged();
    partial void OnN_PhoneChanging(string value);
    partial void OnN_PhoneChanged();
    partial void OnN_HomeChanging(string value);
    partial void OnN_HomeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCodeyChanging(string value);
    partial void OnCodeyChanged();
    partial void OnD_BirthChanging(string value);
    partial void OnD_BirthChanged();
    partial void OnG_BloodChanging(string value);
    partial void OnG_BloodChanged();
    partial void OnN_InsuranceChanging(string value);
    partial void OnN_InsuranceChanged();
    partial void OnGenderChanging(int value);
    partial void OnGenderChanged();
    partial void OnMaritalChanging(int value);
    partial void OnMaritalChanged();
    partial void OnD_E_InsuranceChanging(string value);
    partial void OnD_E_InsuranceChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnGym_IDChanging(int value);
    partial void OnGym_IDChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    partial void OnFullItemChanging(int value);
    partial void OnFullItemChanged();
    #endregion
	
	public tbl_Teacher()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(350)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(MAX)")]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Code", DbType="Int")]
	public System.Nullable<int> R_Code
	{
		get
		{
			return this._R_Code;
		}
		set
		{
			if ((this._R_Code != value))
			{
				this.OnR_CodeChanging(value);
				this.SendPropertyChanging();
				this._R_Code = value;
				this.SendPropertyChanged("R_Code");
				this.OnR_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Date", DbType="NVarChar(50)")]
	public string R_Date
	{
		get
		{
			return this._R_Date;
		}
		set
		{
			if ((this._R_Date != value))
			{
				this.OnR_DateChanging(value);
				this.SendPropertyChanging();
				this._R_Date = value;
				this.SendPropertyChanged("R_Date");
				this.OnR_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Phone", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string N_Phone
	{
		get
		{
			return this._N_Phone;
		}
		set
		{
			if ((this._N_Phone != value))
			{
				this.OnN_PhoneChanging(value);
				this.SendPropertyChanging();
				this._N_Phone = value;
				this.SendPropertyChanged("N_Phone");
				this.OnN_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Home", DbType="NVarChar(15)")]
	public string N_Home
	{
		get
		{
			return this._N_Home;
		}
		set
		{
			if ((this._N_Home != value))
			{
				this.OnN_HomeChanging(value);
				this.SendPropertyChanging();
				this._N_Home = value;
				this.SendPropertyChanged("N_Home");
				this.OnN_HomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(300)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Codey
	{
		get
		{
			return this._Codey;
		}
		set
		{
			if ((this._Codey != value))
			{
				this.OnCodeyChanging(value);
				this.SendPropertyChanging();
				this._Codey = value;
				this.SendPropertyChanged("Codey");
				this.OnCodeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Birth", DbType="NVarChar(50)")]
	public string D_Birth
	{
		get
		{
			return this._D_Birth;
		}
		set
		{
			if ((this._D_Birth != value))
			{
				this.OnD_BirthChanging(value);
				this.SendPropertyChanging();
				this._D_Birth = value;
				this.SendPropertyChanged("D_Birth");
				this.OnD_BirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_Blood", DbType="NVarChar(50)")]
	public string G_Blood
	{
		get
		{
			return this._G_Blood;
		}
		set
		{
			if ((this._G_Blood != value))
			{
				this.OnG_BloodChanging(value);
				this.SendPropertyChanging();
				this._G_Blood = value;
				this.SendPropertyChanged("G_Blood");
				this.OnG_BloodChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Insurance", DbType="NVarChar(150)")]
	public string N_Insurance
	{
		get
		{
			return this._N_Insurance;
		}
		set
		{
			if ((this._N_Insurance != value))
			{
				this.OnN_InsuranceChanging(value);
				this.SendPropertyChanging();
				this._N_Insurance = value;
				this.SendPropertyChanged("N_Insurance");
				this.OnN_InsuranceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int NOT NULL")]
	public int Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marital", DbType="Int NOT NULL")]
	public int Marital
	{
		get
		{
			return this._Marital;
		}
		set
		{
			if ((this._Marital != value))
			{
				this.OnMaritalChanging(value);
				this.SendPropertyChanging();
				this._Marital = value;
				this.SendPropertyChanged("Marital");
				this.OnMaritalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_E_Insurance", DbType="NVarChar(50)")]
	public string D_E_Insurance
	{
		get
		{
			return this._D_E_Insurance;
		}
		set
		{
			if ((this._D_E_Insurance != value))
			{
				this.OnD_E_InsuranceChanging(value);
				this.SendPropertyChanging();
				this._D_E_Insurance = value;
				this.SendPropertyChanged("D_E_Insurance");
				this.OnD_E_InsuranceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this.OnimgChanging(value);
				this.SendPropertyChanging();
				this._img = value;
				this.SendPropertyChanged("img");
				this.OnimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gym_ID", DbType="Int NOT NULL")]
	public int Gym_ID
	{
		get
		{
			return this._Gym_ID;
		}
		set
		{
			if ((this._Gym_ID != value))
			{
				this.OnGym_IDChanging(value);
				this.SendPropertyChanging();
				this._Gym_ID = value;
				this.SendPropertyChanged("Gym_ID");
				this.OnGym_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullItem", DbType="Int NOT NULL")]
	public int FullItem
	{
		get
		{
			return this._FullItem;
		}
		set
		{
			if ((this._FullItem != value))
			{
				this.OnFullItemChanging(value);
				this.SendPropertyChanging();
				this._FullItem = value;
				this.SendPropertyChanged("FullItem");
				this.OnFullItemChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TimeUser")]
public partial class tbl_TimeUser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _UserCodey;
	
	private int _GymID;
	
	private string _Date;
	
	private string _TimeLogin;
	
	private string _TimeOut;
	
	private string _DateWek;
	
	private int _Deleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserCodeyChanging(string value);
    partial void OnUserCodeyChanged();
    partial void OnGymIDChanging(int value);
    partial void OnGymIDChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeLoginChanging(string value);
    partial void OnTimeLoginChanged();
    partial void OnTimeOutChanging(string value);
    partial void OnTimeOutChanged();
    partial void OnDateWekChanging(string value);
    partial void OnDateWekChanged();
    partial void OnDeletedChanging(int value);
    partial void OnDeletedChanged();
    #endregion
	
	public tbl_TimeUser()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCodey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserCodey
	{
		get
		{
			return this._UserCodey;
		}
		set
		{
			if ((this._UserCodey != value))
			{
				this.OnUserCodeyChanging(value);
				this.SendPropertyChanging();
				this._UserCodey = value;
				this.SendPropertyChanged("UserCodey");
				this.OnUserCodeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GymID", DbType="Int NOT NULL")]
	public int GymID
	{
		get
		{
			return this._GymID;
		}
		set
		{
			if ((this._GymID != value))
			{
				this.OnGymIDChanging(value);
				this.SendPropertyChanging();
				this._GymID = value;
				this.SendPropertyChanged("GymID");
				this.OnGymIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeLogin", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TimeLogin
	{
		get
		{
			return this._TimeLogin;
		}
		set
		{
			if ((this._TimeLogin != value))
			{
				this.OnTimeLoginChanging(value);
				this.SendPropertyChanging();
				this._TimeLogin = value;
				this.SendPropertyChanged("TimeLogin");
				this.OnTimeLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOut", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TimeOut
	{
		get
		{
			return this._TimeOut;
		}
		set
		{
			if ((this._TimeOut != value))
			{
				this.OnTimeOutChanging(value);
				this.SendPropertyChanging();
				this._TimeOut = value;
				this.SendPropertyChanged("TimeOut");
				this.OnTimeOutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateWek", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string DateWek
	{
		get
		{
			return this._DateWek;
		}
		set
		{
			if ((this._DateWek != value))
			{
				this.OnDateWekChanging(value);
				this.SendPropertyChanging();
				this._DateWek = value;
				this.SendPropertyChanged("DateWek");
				this.OnDateWekChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Int NOT NULL")]
	public int Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this.OnDeletedChanging(value);
				this.SendPropertyChanging();
				this._Deleted = value;
				this.SendPropertyChanged("Deleted");
				this.OnDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
