<?xml version="1.0" encoding="utf-8"?><Database Name="DB_Sport" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=DB_Sport;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_SportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Admins" Member="tbl_Admins">
    <Type Name="tbl_Admin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="Codey" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GymID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="N_Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="N_Home" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdminLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="D_Birth" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Marital" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullNameGym" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="N_PhoneGym" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AddressGym" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionGym" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="R_DateGym" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="E_DateGym" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DebtGym" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_User" Member="tbl_Users">
    <Type Name="tbl_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="R_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R_Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="N_Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="N_Home" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Codey" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D_Birth" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="G_Blood" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="N_Insurance" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Marital" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="D_E_Insurance" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GymID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OkAdmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullItem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_CMS" Member="tbl_CMs">
    <Type Name="tbl_CM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PanelTitel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextFoter" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="imgTitel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slidimg1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slidimg2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slidimg3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TitelMinAbut" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextMinAbut" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="imgMinAbut" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TitelCart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextCart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberPhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FoterMain" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATitel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATitel1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AText1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATitel2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AText2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATitel3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AText3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATitelCart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATextCart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MapX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MapY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_CostType" Member="tbl_CostTypes">
    <Type Name="tbl_CostType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gym" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_OnlinePayment" Member="tbl_OnlinePayments">
    <Type Name="tbl_OnlinePayment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentIsSuccessful" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PaymentResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentResponseMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentTransactionID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Orders" Member="tbl_Orders">
    <Type Name="tbl_Order">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SansID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Insert" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsFinal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ReportsBuyUser" Member="tbl_ReportsBuyUsers">
    <Type Name="tbl_ReportsBuyUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="N_Buy" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="Money" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Sans" Member="tbl_Sans">
    <Type Name="tbl_San">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SportFildID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SportFild" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GymID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gym" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Techare" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TechareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="D_Start" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D_End" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Days" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Mony" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CostTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SansBuy" Member="tbl_SansBuys">
    <Type Name="tbl_SansBuy">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SansID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SportFild" Member="tbl_SportFilds">
    <Type Name="tbl_SportFild">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GymID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Teacher" Member="tbl_Teachers">
    <Type Name="tbl_Teacher">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="R_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R_Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="N_Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="N_Home" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Codey" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D_Birth" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="G_Blood" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="N_Insurance" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Marital" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="D_E_Insurance" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gym_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullItem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TimeUser" Member="tbl_TimeUsers">
    <Type Name="tbl_TimeUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserCodey" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GymID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeLogin" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeOut" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateWek" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>